#!/usr/bin/env python3
"""
Self-contained reproducible script for XPS peak fit.

Generated by sci-skills-analysis:xps — this file NEVER imports any skill
scripts. It only needs fit.json (produced by fit_peaks.py) + lmfit + matplotlib.
Run with any Python ≥ 3.11 that has lmfit, numpy, matplotlib installed.

Usage:
  python fit_si2p.py            # reads ./fit.json, writes ./fit_si2p_repro.pdf
  python fit_si2p.py fit.json   # explicit input path
"""

import json
import sys
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import ScalarFormatter
from lmfit.models import GaussianModel, LorentzianModel, PseudoVoigtModel, VoigtModel

MODEL_MAP = {
    "gaussian": GaussianModel,
    "lorentzian": LorentzianModel,
    "pseudo_voigt": PseudoVoigtModel,
    "voigt": VoigtModel,
}

# ─── Configuration (auto-filled from fit.json, override if needed) ────────
FIT_JSON = "fit.json"          # path to fit.json from fit_peaks.py
OUTPUT = None                  # set to a path to override auto-naming
# ───────────────────────────────────────────────────────────────────────────


def load_fit(path: str) -> dict:
    with open(path) as f:
        return json.load(f)


def rebuild_model(fit: dict):
    """Rebuild the lmfit model from fit.json peaks and parameters."""
    peak_func = fit.get("peak_function", "pseudo_voigt")
    ModelClass = MODEL_MAP[peak_func]

    composite = None
    params = None

    for i, pk in enumerate(fit["peaks"]):
        prefix = f"p{i}_"
        model = ModelClass(prefix=prefix)

        if composite is None:
            composite = model
        else:
            composite += model

        if params is None:
            params = model.make_params()
        else:
            params.update(model.make_params())

        # Set to fitted values from fit.json
        params[f"{prefix}center"].set(value=pk["center"])
        params[f"{prefix}sigma"].set(value=pk["sigma"])
        params[f"{prefix}amplitude"].set(value=pk["amplitude"])
        if peak_func == "pseudo_voigt" and "fraction" in pk:
            params[f"{prefix}fraction"].set(value=pk["fraction"])

    return composite, params


def plot(fit: dict, model, params, output_path: str) -> None:
    """Draw the same style as plot_region.py: data + baseline + components + envelope."""
    energies = np.array(fit["energies"])
    counts_sub = np.array(fit.get("counts_subtracted", fit["counts_raw"]))
    background = fit.get("background")
    components = model.eval_components(params=params, x=energies)
    envelope = model.eval(params=params, x=energies)
    residual = counts_sub - envelope

    r_squared = 1 - np.sum(residual ** 2) / np.sum((counts_sub - np.mean(counts_sub)) ** 2)

    label = fit.get("region_label", "Region")
    # Morandi palette (matches _plot.py convention)
    cmap = plt.colormaps["tab10"]

    fig, (ax_top, ax_res) = plt.subplots(
        2, 1, figsize=(7, 3.6),
        gridspec_kw={"height_ratios": [4, 1]}, sharex=True,
    )

    # Data
    ax_top.scatter(energies, counts_sub, s=6, color=".3", zorder=10, label="data")
    # Background
    if background:
        ax_top.plot(energies, background, "--", color=".5", lw=1, label="background")
    # Components
    for i, (name, y_comp) in enumerate(components.items()):
        color = cmap(i % 10)
        ax_top.fill_between(energies, background if background else 0, y_comp + (background if background else 0),
                            alpha=0.35, color=color, lw=0)
        ax_top.plot(energies, y_comp + (background if background else 0),
                    color=color, lw=0.8, alpha=0.7)
    # Envelope
    ax_top.plot(energies, envelope + (background if background else 0), "-",
                color=cmap(len(components) % 10), lw=1.2, label="envelope")

    ax_top.set_ylabel("Counts")
    ax_top.legend(fontsize=7, frameon=False, loc="upper left")
    ax_top.set_title(f"{label}   R²={r_squared:.4f}   ({fit['peak_function']})", fontsize=9)

    # Residual
    ax_res.plot(energies, residual, color=".4", lw=0.6)
    ax_res.axhline(0, color=".6", lw=0.5, ls="--")
    ax_res.set_xlabel("Binding Energy (eV)")
    ax_res.set_ylabel("Residual")

    ax_top.invert_xaxis()
    ax_res.invert_xaxis()

    fig.tight_layout()
    fig.savefig(output_path, dpi=200, bbox_inches="tight")
    print(f"Saved: {output_path}", file=sys.stderr)
    plt.close(fig)


def main():
    global FIT_JSON, OUTPUT
    if len(sys.argv) > 1:
        FIT_JSON = sys.argv[1]

    fit = load_fit(FIT_JSON)
    model, params = rebuild_model(fit)

    label = fit.get("region_label", "region").replace(" ", "_")
    out = OUTPUT or f"fit_{label}_repro.pdf"
    plot(fit, model, params, out)


if __name__ == "__main__":
    main()
