#!/usr/bin/env python3
"""
Self-contained reproducible script for XPS peak fit.

Generated by sci-skills-analysis:xps — this file NEVER imports any skill
scripts. It only needs fit.json (produced by fit_peaks.py) + lmfit + matplotlib.
Run with any Python ≥ 3.11 that has lmfit, numpy, matplotlib installed.

Usage:
  python fit_si2p.py            # reads ./fit.json, writes three output files
  python fit_si2p.py fit.json   # explicit input path

Outputs (all in the same directory as this script):
  fit_<label>.pdf   — vector, drag into Origin and ungroup to edit every element
  fit_<label>.png   — raster preview for slides / group meeting
  fit_<label>.csv   — columns: x, y_raw, y1, y2, …, yN, yf
                       drag into Origin to replot with full control
"""

import csv
import json
import sys
from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from lmfit.models import GaussianModel, LorentzianModel, PseudoVoigtModel, VoigtModel

MODEL_MAP = {
    "gaussian": GaussianModel,
    "lorentzian": LorentzianModel,
    "pseudo_voigt": PseudoVoigtModel,
    "voigt": VoigtModel,
}

# ─── Configuration (auto-filled from fit.json, override if needed) ────────
FIT_JSON = "fit.json"          # path to fit.json from fit_peaks.py
OUT_DIR = None                 # output dir (default: same dir as this script)
# ───────────────────────────────────────────────────────────────────────────


def load_fit(path: str) -> dict:
    with open(path) as f:
        return json.load(f)


def rebuild_model(fit: dict):
    """Rebuild the lmfit model from fit.json peaks and parameters."""
    peak_func = fit.get("peak_function", "pseudo_voigt")
    ModelClass = MODEL_MAP[peak_func]

    composite = None
    params = None

    for i, pk in enumerate(fit["peaks"]):
        prefix = f"p{i}_"
        model = ModelClass(prefix=prefix)

        if composite is None:
            composite = model
        else:
            composite += model

        if params is None:
            params = model.make_params()
        else:
            params.update(model.make_params())

        params[f"{prefix}center"].set(value=pk["center"])
        params[f"{prefix}sigma"].set(value=pk["sigma"])
        params[f"{prefix}amplitude"].set(value=pk["amplitude"])
        if peak_func == "pseudo_voigt" and "fraction" in pk:
            params[f"{prefix}fraction"].set(value=pk["fraction"])

    return composite, params


def write_csv(fit, components, envelope, out_dir, label):
    """CSV: x, y_raw, y1, y2, ..., yN, yf  — same format as export_result.py."""
    energies = np.array(fit["energies"])
    y_raw = np.array(fit.get("counts_raw", fit["counts_subtracted"]))
    background = fit.get("background")

    header = ["x", "y_raw"]
    cols = [energies, y_raw]

    for name, y_comp in components.items():
        header.append(name)
        cols.append(y_comp + (np.array(background) if background else 0))

    header.append("yf")
    yf = envelope + (np.array(background) if background else 0)
    cols.append(yf)

    path = out_dir / f"fit_{label}.csv"
    with open(path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(header)
        for row in zip(*cols):
            writer.writerow([f"{v:.6g}" for v in row])
    print(f"Saved: {path}", file=sys.stderr)


def plot(fit, model, params, out_dir, label):
    """PDF (vector) + PNG (raster preview)."""
    energies = np.array(fit["energies"])
    counts_sub = np.array(fit.get("counts_subtracted", fit["counts_raw"]))
    background = fit.get("background")
    components = model.eval_components(params=params, x=energies)
    envelope = model.eval(params=params, x=energies)
    residual = counts_sub - envelope

    r_squared = 1 - np.sum(residual ** 2) / np.sum((counts_sub - np.mean(counts_sub)) ** 2)

    region_label = fit.get("region_label", "Region")
    cmap = plt.colormaps["tab10"]

    fig, (ax_top, ax_res) = plt.subplots(
        2, 1, figsize=(7, 3.6),
        gridspec_kw={"height_ratios": [4, 1]}, sharex=True,
    )

    ax_top.scatter(energies, counts_sub, s=6, color=".3", zorder=10)
    if background:
        ax_top.plot(energies, background, "--", color=".5", lw=1)

    for i, (name, y_comp) in enumerate(components.items()):
        color = cmap(i % 10)
        y_bottom = np.array(background) if background else 0
        ax_top.fill_between(energies, y_bottom, y_comp + y_bottom,
                            alpha=0.35, color=color, lw=0)
        ax_top.plot(energies, y_comp + y_bottom, color=color, lw=0.8, alpha=0.7)

    y_bottom = np.array(background) if background else 0
    ax_top.plot(energies, envelope + y_bottom, "-",
                color=cmap(len(components) % 10), lw=1.2)

    ax_top.set_ylabel("Counts")
    ax_top.set_title(f"{region_label}   R²={r_squared:.4f}   ({fit.get('peak_function','?')})",
                     fontsize=9)

    ax_res.plot(energies, residual, color=".4", lw=0.6)
    ax_res.axhline(0, color=".6", lw=0.5, ls="--")
    ax_res.set_xlabel("Binding Energy (eV)")
    ax_res.set_ylabel("Residual")

    ax_top.invert_xaxis()
    ax_res.invert_xaxis()
    fig.tight_layout()

    # PDF — vector, Origin-editable
    pdf_path = out_dir / f"fit_{label}.pdf"
    fig.savefig(pdf_path, dpi=200, bbox_inches="tight")
    print(f"Saved: {pdf_path}", file=sys.stderr)

    # PNG — raster preview
    png_path = out_dir / f"fit_{label}.png"
    fig.savefig(png_path, dpi=200, bbox_inches="tight")
    print(f"Saved: {png_path}", file=sys.stderr)

    plt.close(fig)

    return components, envelope


def main():
    global FIT_JSON, OUT_DIR
    if len(sys.argv) > 1:
        FIT_JSON = sys.argv[1]

    fit = load_fit(FIT_JSON)
    model, params = rebuild_model(fit)

    label = fit.get("region_label", "region").replace(" ", "_")
    out_dir = OUT_DIR or Path(__file__).resolve().parent
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    components, envelope = plot(fit, model, params, out_dir, label)
    write_csv(fit, components, envelope, out_dir, label)


if __name__ == "__main__":
    main()
